# ============================================================
#  run.mac  —  run en mode batch
#  Usage : ./sim run.mac
# ============================================================

/run/initialize

# ------------------------------------------------------------
#  Épaisseur du béton (modifier selon le besoin)
# ------------------------------------------------------------
/det/setConcreteThickness 2000 mm

# ------------------------------------------------------------
#  Modèle de distribution angulaire des muons :
#    0 = cos²θ        (approximation Terre plate, Eq.11)
#                     Valide pour θ < 70°, formule classique
#    1 = D(θ)         (Terre sphérique, Eq.9)
#                     Meilleure description à grand angle (>70°)
#                     Paramètre R/d = 174 (Shukla & Sankrith 2016)
# ------------------------------------------------------------
/gun/angularModel 1

# ------------------------------------------------------------
#  Nombre de muons à simuler
# ------------------------------------------------------------
/run/beamOn 5000
